const MENU=[
['Breakfast & Hot Sips',[['Kadak Chai',30],['Hot Coffee',40],['Green Tea',40],['Boiled Eggs (3 pcs)',50],['Scrambled Eggs (3 pcs)',70],['Classic Omelette',90]]],
['Cold Coffees',[['Classic Cold Coffee',70],['Vanilla Cold Coffee',80],['Dark Choco Coffee',90],['Hazelnut Cold Coffee',100],['Caramel Cold Coffee',110],['Salted Caramel Coffee',110],['Cookies & Cream Coffee',110],['Oreo Cold Coffee',110]]],
['Iced Teas & Coolers',[['Virgin Mojito',80],['Blue Lagon',90],['Green Apple Cooler',90],['Watermelon Cooler',99],['Kiwi Cooler',99],['Peach Iced Tea',99],['Lemon Iced Tea',99]]],
['Burgers & Sandwiches',[['Classic Veg Burger',80],['Loaded Cheese Burger',100],['Crispy Chicken Burger',150],['Loaded Chicken Cheese Burger',170],['Grilled Veg Sandwich',100],['Paneer Tikka Sandwich',120],['Cheese & Corn Sandwich',150],['Grilled Chicken Sandwich',150],['Chicken Cheese Sandwich',160],['Peri Peri Chicken Sandwich',160]]],
['Fries & Nachos',[['Classic Salted Fries',80],['Peri Peri Fries',110],['Cheesy Fries',110],['Loaded Cheese Fries',130],['Mexican Loaded Fries',150],['Chilli Cheese Fries',150],['Classic Nachos',130],['Cheesy Nachos',140],['Chicken Nachos',190],['Peri Peri Chicken Nachos',200]]],
['Maggi Bowls',[['Classic Butter Maggi',50],['Masala Veggie Maggi',80],['Cheesy Maggi',90],['Corn & Cheese Maggi',90],['Peri Peri Cheese Maggi',100]]],
['Pastas',[['Classic White Sauce Pasta',110],['Classic Red Sauce Pasta',120],['Creamy Pink Sauce Pasta',130],['Chicken White Sauce Pasta',190],['Chicken Red Sauce Pasta',200],['Chicken Pink Sauce Pasta',210]]]
].flatMap(([category,items])=>items.map(([name,price])=>({id:name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,price,category}))); 
const app=document.getElementById('app');const S={view:'home',item:null,q:'',cart:JSON.parse(localStorage.getItem('ctCart')||'[]'),ref:null};const cats=[...new Set(MENU.map(x=>x.category))];
const money=n=>'₹'+n, esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem('ctCart',JSON.stringify(S.cart))}function total(){return S.cart.reduce((a,x)=>a+x.price*x.qty,0)}function count(){return S.cart.reduce((a,x)=>a+x.qty,0)}
function go(v,item=null){history.pushState({},'',v==='home'?location.pathname:v==='menu'?location.pathname+'?view=menu':location.pathname+'?view=product&item='+encodeURIComponent(item));S.view=v;S.item=item;render();scrollTo(0,0)}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1500)}
function home(){app.innerHTML='<main class="page home"><section class="card"><div class="brand"><span class="dot"></span>Digital Menu</div><h1 class="display">Cafe<br>There.</h1><p class="copy">A warm little menu for good coffee, easy bites and unhurried moments.</p><button class="btn" id="open">Open Menu →</button><p>Scan. Tap. Browse. No app or download needed.</p></section></main>';document.getElementById('open').onclick=()=>go('menu')}
function menu(){const q=S.q.toLowerCase().trim();const filtered=MENU.filter(x=>!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q));const groups=cats.map(c=>[c,filtered.filter(x=>x.category===c)]).filter(([,a])=>a.length);app.innerHTML=`<main class="page"><header class="top"><div class="row"><button class="icon" id="home">←</button><div class="wordmark">Cafe There</div><button class="icon" id="cart">🛒<span class="badge">${count()}</span></button></div><input class="search" id="search" placeholder="Search coffee, burger, pasta…" value="${esc(S.q)}"></header><div class="intro"><span class="eyebrow">Cafe There</span><h1>Today's menu.</h1><p>Choose your items, add them to your order, then pay at the counter.</p></div><nav class="cats">${cats.map(c=>`<button class="pill" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</nav>${groups.length?groups.map(([c,a])=>`<section class="section" id="${slug(c)}"><div class="head"><h2 class="section-title">${esc(c)}</h2><span class="count">${a.length} items</span></div><div class="items">${a.map(x=>`<button class="item" data-item="${x.id}"><span><span class="name">${esc(x.name)}</span><span class="meta">${esc(x.category)}</span></span><span class="price">${money(x.price)}</span></button>`).join('')}</div></section>`).join(''):'<div class="card"><b>No matches</b><p>Try another item.</p></div>'}</main>`;home.onclick=()=>go('home');cart.onclick=()=>{S.view='cart';render()};search.oninput=e=>{S.q=e.target.value;menu();document.getElementById('search').focus()};document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>go('product',b.dataset.item));document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>document.getElementById(slug(b.dataset.cat))?.scrollIntoView({behavior:'smooth'}))}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function product(){const x=MENU.find(a=>a.id===S.item);if(!x)return go('menu');const n=S.cart.find(a=>a.id===x.id)?.qty||0;app.innerHTML=`<main class="page"><section class="detailhero"><button class="icon" id="back">←</button><span class="placeholder">Food image coming soon</span></section><section class="detail"><span class="eyebrow">${esc(x.category)}</span><h1 class="title">${esc(x.name)}</h1><div class="detailprice">${money(x.price)}</div><p>A Cafe There menu item. Food photography and descriptions can be added later.</p><button class="btn full" id="add">${n?'Add another · '+n+' in order':'Add to order'} +</button><p>Payment is made at the counter.</p></section></main>`;back.onclick=()=>go('menu');add.onclick=()=>{const e=S.cart.find(a=>a.id===x.id);if(e)e.qty++;else S.cart.push({...x,qty:1});save();toast('Added to your order');product()}}
function cart(){if(!S.cart.length){app.innerHTML='<main class="page"><header class="top"><div class="row"><button class="icon" id="back">←</button><div class="wordmark">Your Order</div><span></span></div></header><div class="intro"><span class="eyebrow">Cafe There</span><h1>Your order is empty.</h1><p>Add something from the menu.</p></div><button class="btn" id="browse">Browse Menu →</button></main>';back.onclick=()=>go('menu');browse.onclick=()=>go('menu');return}app.innerHTML=`<main class="page"><header class="top"><div class="row"><button class="icon" id="back">←</button><div class="wordmark">Your Order</div><span></span></div></header><div class="intro"><span class="eyebrow">Cafe There</span><h1>Ready to order?</h1><p>Review your items. You'll pay at the counter.</p></div><section class="cart">${S.cart.map(x=>`<div class="order"><div><b>${esc(x.name)}</b><small>${money(x.price)} each</small></div><div class="qty"><button data-q="${x.id}" data-d="-1">−</button><b>${x.qty}</b><button data-q="${x.id}" data-d="1">+</button></div><b class="price">${money(x.price*x.qty)}</b></div>`).join('')}<div class="total"><span>Total</span><strong>${money(total())}</strong></div></section><section class="pay"><strong>Pay at the counter</strong><p>Place your order from your phone, then show the order reference at the counter and pay there.</p></section><button class="btn full" id="place">Place Order · ${money(total())}</button><p>This first version keeps the order on this device. Staff connection comes next.</p></main>`;back.onclick=()=>go('menu');document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const x=S.cart.find(a=>a.id===b.dataset.q);x.qty+=+b.dataset.d;if(x.qty<1)S.cart=S.cart.filter(a=>a.id!==x.id);save();cart()});place.onclick=()=>{S.ref='CT-'+Math.random().toString(36).slice(2,8).toUpperCase();S.cart=[];save();confirmation()}}
function confirmation(){app.innerHTML=`<main class="page home"><section class="card"><div class="brand"><span class="dot"></span>Cafe There</div><div class="success">✓</div><span class="eyebrow">Order received</span><h1 class="title">Order ${S.ref}</h1><p class="copy">Please show this reference at the counter and make your payment there.</p><div class="pay"><strong>Payment: At counter</strong><p>Your order will be connected to the staff dashboard in the next phase.</p></div><button class="btn full" id="continue">Continue browsing →</button></section></main>`;document.getElementById('continue').onclick=()=>go('menu')}
function render(){S.view==='home'?home():S.view==='menu'?menu():S.view==='product'?product():S.view==='cart'?cart():confirmation()}window.onpopstate=()=>{const p=new URLSearchParams(location.search);S.view=p.get('view')==='menu'?'menu':p.get('view')==='product'?'product':'home';S.item=p.get('item');render()};render();
